[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/metamob-proxy/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
